import type { Metadata } from 'next';
import { Poppins, Inter_Tight } from 'next/font/google';
import { ContextProvider } from './Context';
import './globals.css';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  subsets: ['latin'],
});

const inter = Inter_Tight({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${inter.variable} bg-color-primary`}>
        <ContextProvider>
          <div className="flex flex-col justify-between bg-color-secondary rounded-[2rem] p-8 max-w-[80rem] min-h-screen mx-auto my-[4vw] sm:p-12">
            {children}
            <footer>Batuhan Kendirli</footer>
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
