import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  style: ['normal'],
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex flex-col justify-between bg-slate-800 rounded-md p-8 max-w-[80rem] min-h-screen mx-auto my-[4vw] sm:p-12">
          {children}
          <footer>Batuhan Kendirli</footer>
        </div>
      </body>
    </html>
  );
}
